// IMPORTANT: Replace this file with the one generated by:
// flutterfire configure
//
// Run this command in your project root after setting up Firebase:
// dart pub global activate flutterfire_cli
// flutterfire configure
//
// This will auto-generate the correct firebase_options.dart for your project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'No Web Firebase options configured. Run: flutterfire configure',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⚠️ REPLACE THESE WITH YOUR ACTUAL FIREBASE CONFIG VALUES

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtGD-uPf6BvvejbUl9x__A7uk9Zu2gQ3o',
    appId: '1:519520193791:android:76b1e9a549a6ffe54e10ca',
    messagingSenderId: '519520193791',
    projectId: 'internee-pk-ims',
    storageBucket: 'internee-pk-ims.firebasestorage.app',
  );

  // Get them from: Firebase Console → Project Settings → Your Apps

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.internManagement',
  );
}