// IMPORTANT: Replace this file with the one generated by:
// flutterfire configure
//
// Run this command in your project root after setting up Firebase:
// dart pub global activate flutterfire_cli
// flutterfire configure
//
// This will auto-generate the correct firebase_options.dart for your project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⚠️ REPLACE THESE WITH YOUR ACTUAL FIREBASE CONFIG VALUES

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCyPRpN9tf3PAO_spi11xW_OCQ4CbodOns",
      authDomain: "internee-pk-ims.firebaseapp.com",
      projectId: "internee-pk-ims",
      storageBucket: "internee-pk-ims.firebasestorage.app",
      messagingSenderId: "519520193791",
      appId: "1:519520193791:web:86b1fc17a73fa9524e10ca");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtGD-uPf6BvvejbUl9x__A7uk9Zu2gQ3o',
    appId: '1:519520193791:android:76b1e9a549a6ffe54e10ca',
    messagingSenderId: '519520193791',
    projectId: 'internee-pk-ims',
    storageBucket: 'internee-pk-ims.firebasestorage.app',
  );

  // Get them from: Firebase Console → Project Settings → Your Apps

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtGD-uPf6BvvejbUl9x__A7uk9Zu2gQ3o',
    appId: '1:519520193791:ios:81bdb2d2b8bf0f234e10ca',
    messagingSenderId: '519520193791',
    projectId: 'internee-pk-ims',
    storageBucket: 'internee-pk-ims.firebasestorage.app',
    iosBundleId: 'com.example.internManagement',
  );
}
